name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  NODE_VERSION: "16"

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup PKG
        run: npm i -g pkg

      - name: chmod
        run: chmod -R +x ./.github

      - name: Install dependencies
        run: npm ci

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build
        run: npm run build

      - name: Create PKG
        run: pkg ./package.json

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: "dist/rpg-board-project-backend"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT_AFTER: |
            ${{ secrets.TARGET_DIR }}/rpg-board-project-backend

    
